# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/hard_projects/wave_producer/dds_1/dds_1.cache/wt [current_project]
set_property parent.project_path F:/hard_projects/wave_producer/dds_1/dds_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/soft_projects/fpga_minist/code/mnist_fpga-master/mnist_fpga-master/ipcore_dir
  f:/hard_projects/wave_producer/dds_1/dds_1.srcs/sources_1/ip
  f:/hard_projects/wave_producer/dds_1/dds_1.srcs/sources_1/ip/dds_addr
  f:/hard_projects/wave_producer/dds_1/dds_1.srcs/sources_1
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet F:/hard_projects/wave_producer/dds_1/dds_1.runs/dds_addr_0_synth_1/dds_addr_0.dcp
set_property used_in_implementation false [get_files F:/hard_projects/wave_producer/dds_1/dds_1.runs/dds_addr_0_synth_1/dds_addr_0.dcp]
add_files -quiet F:/hard_projects/wave_producer/dds_1/dds_1.runs/rom_synth_1/rom.dcp
set_property used_in_implementation false [get_files F:/hard_projects/wave_producer/dds_1/dds_1.runs/rom_synth_1/rom.dcp]
read_verilog -library xil_defaultlib F:/hard_projects/wave_producer/dds_1/dds_1.srcs/sources_1/new/dds_main.v
synth_design -top dds_main -part xc7z020clg400-2
write_checkpoint -noxdef dds_main.dcp
catch { report_utilization -file dds_main_utilization_synth.rpt -pb dds_main_utilization_synth.pb }
